name: InSignsPlus
main: com.empcraft.InSignsExtended
version: 0.6.0
author: Empire92
website: www.empcraft.com
softdepend: [InSigns]
depend: [Vault,ProtocolLib]
commands:
   isp:
      description: InSignsPlus commands.