name: InSignsPlus
main: com.empcraft.InSignsPlus
version: 0.7.4
author: Empire92
website: www.empcraft.com
softdepend: [InSigns]
depend: [Vault,ProtocolLib]
commands:
   isp:
      description: InSignsPlus commands.